### ISSUE TITLE
Code unavailable

### ISSUE THREAD

**Issue by tavy14t** [anacrolix/anacrolix#1]
I found your comment (on stackoverflow) about this program, but I think you removed some files from the project.

"Nah! Call ptrace() with PTRACE ATTACH. Then open /proc/<pid>/mem, seek to the region offset, and read the length of the region as given in /proc</pid>/maps.

Here's a program I wrote that does it in C. Here's a module I wrote that does it in Python (and the ptrace binding). For the finish, a program that dumps all regions of a process to files."

Can you upload them back on github ?

**Comment by jewelfish** [comment]
Good day

I think there is a mistake: I never wrote that comment.

Are you sure it's me?
If so, would you kindly provide link to the thread?

Thank you
Il 22/giu/2016 10:23, "tavy14t" <notifications@github.com> ha scritto:

I found your comment (on stackoverflow) about this program, but I think you
removed some files from the project.

"Nah! Call ptrace() with PTRACE ATTACH. Then open /proc//mem, seek to the
region offset, and read the length of the region as given in /proc/maps.

Here's a program I wrote that does it in C. Here's a module I wrote that
does it in Python (and the ptrace binding). For the finish, a program that
dumps all regions of a process to files."

Can you upload them back on github ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/anacrolix/anacrolix/issues/1>, or mute the thread
<https://github.com/notifications/unsubscribe/APSw1DW_ePqgh7752fx7mkl1akPCBRc2ks5qOPD0gaJpZM4I7hR->
.

**Comment by tavy14t** [comment]
This is the thread where I found your comment.
https://stackoverflow.com/questions/3342335/dump-memory-of-a-process

**Comment by jewelfish** [comment]
Oh I see...
I'm not Matt Joiner.

Sorry: didn't see I was in Carbon Copy.

Sorry about that.

Let's wait for Matt "anacrolix" Joiner to answer your question.


Still... I don't get how my email got in the cc list in the first place...


On Wed, Jun 22, 2016 at 10:44 AM, tavy14t <notifications@github.com> wrote:

> This is the thread where I found your comment.
> https://stackoverflow.com/questions/3342335/dump-memory-of-a-process
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/anacrolix/anacrolix/issues/1#issuecomment-227680640>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APSw1Kg9i5MO8v7ncwxG8XwIEjdewV_Nks5qOPYFgaJpZM4I7hR->
> .
>



-- 

------------------------------------------------------------------
---| Linkedin - Curriculum vitae
<https://www.linkedin.com/in/marcokobepaolini> |---
---| Behance -  Portfolio <https://www.behance.net/yakumokobe>
  |---

**Comment by anacrolix** [comment]
Hi, the code was hosted on code.google.com, and you're not being redirected correctly. I'll update the links now.

**Comment by anacrolix** [comment]
Seems I've lost the repo, I'm restoring it from a backup from 2012.

**Comment by anacrolix** [comment]
I've fixed that. Hopefully I'll find the rest of the repo sometime, but all the links now work on the SO answer.
